/**
 * Admin API — Supabase Edge Function
 *
 * Uses admin token (not Supabase auth) for authentication + authorization.
 * Admin token is generated by admin-auth edge function.
 *
 * Authorization: Bearer <admin-token>
 * Body: { action, ... }
 *
 * Actions:
 *   check_admin         → { role }
 *   list_users          → { users, total }
 *   get_user (user_id)  → { user, trades, stats }
 *   update_user (user_id, ...) → { success }
 *   get_logs (page, limit, user_id) → { logs, total }
 *   get_config          → { config }
 *   update_config (key, value) → { success }
 */
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { logAudit, Action } from '../_shared/logger.ts';
import { extractAdminToken, verifyAdminToken, adminCorsHeaders } from '../_shared/admin-auth.ts';

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { ...adminCorsHeaders, 'Content-Type': 'application/json' } });
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: adminCorsHeaders });

  try {
    // ---- AUTH via admin token (NOT Supabase auth) ----
    const authHeader = req.headers.get('Authorization');
    const rawToken = extractAdminToken(authHeader);
    if (!rawToken) return json({ error: 'Unauthorized — no token' }, 401);

    const payload = await verifyAdminToken(rawToken);
    if (!payload.isValid) return json({ error: 'Unauthorized — invalid or expired token' }, 401);

    const adminEmail = payload.email;
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Parse body
    const body: any = req.method === 'POST' ? await req.json() : {};
    const action = new URL(req.url).searchParams.get('action') || body.action;
    const requestBody = { ...body, action };
    const ipAddress = req.headers.get('x-forwarded-for') || '';

    // ---- check_admin (used by AdminGuard on client) ----
    if (action === 'check_admin') {
      return json({ success: true, data: { role: 'superadmin', email: adminEmail } });
    }

    // ---- list_users ----
    if (action === 'list_users') {
      const page = Math.max(1, parseInt(body.page || '1'));
      const limit = Math.min(100, Math.max(1, parseInt(body.limit || '20')));
      const offset = (page - 1) * limit;

      const { data: users, error: uErr, count } = await supabase
        .from('profiles')
        .select('id, full_name, email, avatar_url, exchange, current_phase, is_early_adopter, subscription_plan, onboarding_completed, preferred_lang, preferred_theme, auth_provider, created_at, updated_at', { count: 'exact' })
        .order('created_at', { ascending: false })
        .range(offset, offset + limit - 1);

      if (uErr) return json({ error: 'Failed to fetch users', detail: uErr.message }, 500);

      await logAudit(supabase, { userId: 'admin', userEmail: adminEmail, action: Action.ADMIN_LIST_USERS, functionName: 'admin-api', requestBody, responseStatus: 200, ipAddress });
      return json({ success: true, data: users || [], total: count || 0, page, limit });
    }

    // ---- get_user ----
    if (action === 'get_user') {
      const targetId = body.user_id;
      if (!targetId) return json({ error: 'user_id required' }, 400);

      const { data: user, error: tErr } = await supabase
        .from('profiles')
        .select('id, full_name, email, avatar_url, exchange, current_phase, is_early_adopter, subscription_plan, onboarding_completed, preferred_lang, preferred_theme, auth_provider, created_at, updated_at')
        .eq('id', targetId)
        .single();
      if (tErr || !user) return json({ error: 'User not found' }, 404);

      const { data: trades } = await supabase.from('trades').select('*').eq('user_id', targetId).order('opened_at', { ascending: false }).limit(50);
      const { data: stats } = await supabase.from('daily_stats').select('*').eq('user_id', targetId).order('date', { ascending: false }).limit(30);

      return json({ success: true, data: { user, trades: trades || [], stats: stats || [] } });
    }

    // ---- update_user ----
    if (action === 'update_user') {
      const { user_id, current_phase, onboarding_completed, exchange } = body;
      if (!user_id) return json({ error: 'user_id required' }, 400);
      const updates: Record<string, unknown> = {};
      if (current_phase !== undefined) updates.current_phase = current_phase;
      if (onboarding_completed !== undefined) updates.onboarding_completed = onboarding_completed;
      if (exchange !== undefined) updates.exchange = exchange;
      if (Object.keys(updates).length === 0) return json({ error: 'No fields to update' }, 400);

      const { error: upErr } = await supabase.from('profiles').update(updates).eq('id', user_id);
      if (upErr) return json({ error: 'Update failed', detail: upErr.message }, 500);
      return json({ success: true });
    }

    // ---- get_logs ----
    if (action === 'get_logs') {
      const page = Math.max(1, parseInt(body.page || '1'));
      const limit = Math.min(200, Math.max(1, parseInt(body.limit || '50')));
      const offset = (page - 1) * limit;
      const userIdFilter = body.user_id || null;

      let query = supabase.from('audit_logs').select('*', { count: 'exact' });
      if (userIdFilter) query = query.eq('user_id', userIdFilter);
      query = query.order('created_at', { ascending: false }).range(offset, offset + limit - 1);

      const { data: logs, error: lErr, count } = await query;
      if (lErr) return json({ error: 'Failed to fetch logs', detail: lErr.message }, 500);
      return json({ success: true, data: logs || [], total: count || 0, page, limit });
    }

    // ---- get_config ----
    if (action === 'get_config') {
      const { data: configRows } = await supabase.from('app_config').select('key, value');
      const config: Record<string, unknown> = {};
      if (configRows) for (const row of configRows) config[row.key] = row.value;
      return json({ success: true, data: config });
    }

    // ---- update_config ----
    if (action === 'update_config') {
      // Only ADMIN_EMAIL holder can update config
      const adminEmailFromEnv = Deno.env.get('ADMIN_EMAIL');
      if (adminEmail !== adminEmailFromEnv) return json({ error: 'Only superadmin can update config' }, 403);
      const { key, value } = body;
      if (!key) return json({ error: 'key required' }, 400);
      const { error: upErr } = await supabase.from('app_config').upsert({ key, value: typeof value === 'string' ? JSON.parse(value) : value }, { onConflict: 'key' });
      if (upErr) return json({ error: 'Update failed', detail: upErr.message }, 500);
      return json({ success: true });
    }

    return json({ error: `Unknown action: ${action}` }, 400);
  } catch (error: any) {
    console.error('Admin API error:', error?.message || error);
    return json({ error: error?.message || 'Internal server error' }, 500);
  }
});
